### ISSUE TITLE
Package version

### ISSUE THREAD

**Issue by VLucet** [simonmoulds/r_lulcc#7]
Cran version is 1.0.4, while current source code version in 1.0.2. I have noticed differences between the CRAN bundle and this github version. For instance, the code was differing for `crossTabulate` (which I fixed). Is there more updates to be merged into the current github source code so that we are on par with CRAN 1.0.4?

**Comment by VLucet** [comment]
I can start comparing file by file but @simonmoulds maybe you can point me toward some specific things.

**Comment by simonmoulds** [comment]
I'm not sure - I only have one version on my laptop so I'm not sure how the discrepancy arose. Probably just carelessness on my part - forgetting to upload changes to Github. Yes, if you can do a file comparison that would be great. Changes would have been most likely in the allocation functions.

**Comment by VLucet** [comment]
Will do

**Comment by VLucet** [comment]
It seems like it was only the `crossTabulate` that was in this situation. Moving the package version to 1.0.5 as the github version of the code is now ahead of CRAN.
